version:                                 "3"
services:
  bifrostpostgres:
      image:                             postgres
      container_name:                    postgres-bifrost
      restart:                           unless-stopped
      volumes:
        - ~/stellar/bifrost/postgresql:/var/lib/postgresql/data
      environment:
        POSTGRES_USER:                   stellar
        POSTGRES_PASSWORD:               password
        POSTGRES_DB:                     bifrostdb
      networks:
          - stellarbitcoin_default
          - stellarethereum_default
          - stellarcorehorizon_default
          - default

  bifrost:
      build:                             ./bifrost-docker
      container_name:                    stellar-bifrost
      volumes:
        - ~/stellar/bifrost:/opt/bifrost
      restart:                           unless-stopped
      depends_on:
        - bifrostpostgres
      environment:
        POSTGRES_USER:                   stellar
        POSTGRES_PASSWORD:               password
        MASTER_PUBLIC_KEY:               "xpub6E9BpPGtKfgwCzJY4Jjb6MwUqzhCZuRF3n1vTXLfJYSH9F8gXm4pdVTphVEv419wZBSq9vUJCnzWLZcnhvmq88wnVpyaeEiCMKH4ndtKSDe"
        BIFROST_BITCOIN_RPC_SERVER:      "bitcoind:18332"
        RPC_USER:                        "user"
        RPC_PASS:                        "password"
        TESTNET:                         "true"
        MINIMUM_VALUE_BTC:               "0.00001"
        TOKEN_PRICE_BTC:                 "10000"
        BIFROST_ETHEREUM_RPC_SERVER:     "ethereum:8545"
        NETWORK_ID:                      "4"
        MINIMUM_VALUE_ETH:               "0.00001"
        TOKEN_PRICE_ETH:                 "1000"
        STELLAR_ISSUER_PUBLIC_KEY:       "GAVQKHDYK4OMYLOZFBQECEEDYHCZDKLOZUWSO6PSBJGGJVPZA4ZXY7AU"
        STELLAR_DISTRIBUTION_PUBLIC_KEY: "GDF7J32UEXYUJNPOF4T3CSYKSCF7QGFCZDCQGHHTCRGD6SH4WXWHVDT5"
        STELLAR_SIGNER_SECRET_KEY:       "SBQNXDJ5OKXBXAI5YMZVE4KWJO7BHHYMKWWTAFPVVGLP62CAPFY6WAX2"
        TOKEN_ASSET_CODE:                "HAIRBALZ"
        NEEDS_AUTHORIZE:                 "false"
        STELLAR_HORIZON:                 "http://stellarhorizon:8000"
        NETWORK_PASSPHRASE:              "Test SDF Network ; September 2015"
        STARTING_BALANCE:                "4"
        BIFROST_DB_TYPE:                 "postgres"
        BIFROST_DB_DSN:                  "postgres://stellar:password@bifrostpostgres/bifrostdb?sslmode=disable"
      ports:
        - "8800:8800"
      networks:
          - stellarbitcoin_default
          - stellarethereum_default
          - stellarcorehorizon_default
          - default

networks:
  stellarbitcoin_default:
    external:                            true
  stellarethereum_default:
    external:                            true
  stellarcorehorizon_default:
    external:                            true
