version:                                   "3"
services:
  bifrostpostgres:
      image:                               postgres
      container_name:                      postgres-bifrost
      restart:                             unless-stopped
      volumes:
        - ~/stellar/bifrost/postgresql:/var/lib/postgresql/data
      environment:
        POSTGRES_USER:                     stellar
        POSTGRES_PASSWORD:                 password
        POSTGRES_DB:                       bifrostdb
      network_mode: "host"
      networks:
          - stellarbitcoin_default
          - stellarethereum_default
          - stellarcorehorizon_default
          - default

  bifrost:
      build:                               ./bifrost-docker
      container_name:                      stellar-bifrost
      volumes:
        - ~/stellar/bifrost:/opt/bifrost
      restart:                             unless-stopped
      depends_on:
        - bifrostpostgres
      environment:
        POSTGRES_USER:                     stellar
        POSTGRES_PASSWORD:                 password
        MASTER_PUBLIC_KEY:                 "xpub661MyMwAqRbcFoPVgm64oXHuLPXLfNkM7Q2MLHZvPH1frpNvRRPLgARvbwgGR83wtxCafi7ar32y7gzAp9t1ZLrxpVK6nRoYRBKWqPyaYBY"
        BIFROST_BITCOIN_RPC_SERVER:        "bitcoind:18332"
        RPC_USER:                          "bitcoin-core-user"
        RPC_PASS:                          "NW#+ph!p2f#DBRk+9$hxc9P"
        TESTNET:                           "true"
        MINIMUM_VALUE_BTC:                 "0.00001"
        BIFROST_ETHEREUM_RPC_SERVER:       "ethereum:8545"
        NETWORK_ID:                        "4"
        MINIMUM_VALUE_ETH:                 "0.00001"
        BIFROST_STELLAR_ISSUER_PUBLIC_KEY: "GATIJXESQLVCNWKQ3D6N6RMKTTEZARGMPKY4IGZD2CBJUEEVX3RTPH6K"
        BIFROST_STELLAR_SIGNER_SECRET_KEY: "SBXERYZ5S2LJT6WXSWQEZ5ACALKKQBMUILHL7GKXGUIMG4JHXFE7WEUZ"
        TOKEN_ASSET_CODE:                  "LMB"
        NEEDS_AUTHORIZE:                   "false"
        BIFROST_STELLAR_HORIZON:           "http://stellarhorizon:8000"
        NETWORK_PASSPHRASE:                "Test SDF Network ; September 2015"
        BIFROST_DB_TYPE:                   "postgres"
        BIFROST_DB_DSN:                    "postgres://stellar:password@bifrostpostgres/bifrostdb?sslmode=disable"
      ports:
        - "8800:8800"
      network_mode: "host"
      networks:
          - stellarbitcoin_default
          - stellarethereum_default
          - stellarcorehorizon_default
          - default

networks:
  stellarbitcoin_default:
    external:                              true
  stellarethereum_default:
    external:                              true
  stellarcorehorizon_default:
    external:                              true
